### ISSUE TITLE
Luminousttv

### ISSUE THREAD

**Issue by DannyDarth** [2bc4/streamlink-ttvlol#2]
This is what happens when using luminous.

`Found matching plugin twitch for URL twitch.tv/shotz
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D604495%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D604495%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72E2F80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Waiting for streams, retrying every 1.0 second(s)
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D742125%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D742125%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72A84F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D25622%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D25622%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72E3A90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D414544%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D414544%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72A9390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D266756%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D266756%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE71B0670>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D42032%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D42032%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72AA6B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D320279%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D320279%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72A81F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D4122%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D4122%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72E3D60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D808984%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D808984%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72AA860>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D459169%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D459169%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72A97B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D862416%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D862416%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72E3490>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D810474%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D810474%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72A99C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D742041%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D742041%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72A87F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D145783%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D145783%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72E36A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D27701%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D27701%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72A8AF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D277695%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D277695%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72AAB90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D620042%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D620042%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72A99C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D480936%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D480936%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72A8820>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D535540%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D535540%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72E3A90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D936161%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D936161%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE8260D00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D692602%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D692602%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72A93F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D277431%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D277431%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72ABEB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D847951%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D847951%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72A95A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D902203%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D902203%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72AB6D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D336242%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D336242%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72E3370>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D384681%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D384681%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE8260CD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D826168%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D826168%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72A8D60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D277375%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D277375%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72ABA00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D161849%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D161849%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72E36A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D840014%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D840014%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72A8E20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D205862%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D205862%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72A8D90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D940010%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D940010%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72E3910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D314357%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D314357%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72AB880>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D150857%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D150857%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72A97B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D485632%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D485632%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72E3550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D109707%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D109707%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72A99C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D964473%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D964473%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72AB730>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D720666%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D720666%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72E3F40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Unable to open URL: http://localhost:9595/playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D647502%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (HTTPConnectionPool(host='localhost', port=9595): Max retries exceeded with url: /playlist/shotz.m3u8%3Fplayer%3Dtwitchweb%26p%3D647502%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3DTrue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CE72A9930>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))`

**Comment by Sokoloft** [comment]
Are you running the luminous-ttv.exe? That needs to be open and running in the background so that it can handle requests. If it isn't running, you'll get that error.

**Comment by DannyDarth** [comment]
> Are you running the luminous-ttv.exe? That needs to be open and running in the background so that it can handle requests. If it isn't running, you'll get that error.
> 
> If you are running luminous. Does it say anything in the prompt? If not, try launching it with the --debug parameter.

ohhh i guess thats why. Yeah i didn't have the exe running.
