### ISSUE TITLE
How about adding proxy list function?

### ISSUE THREAD

**Issue by ketersu** [2bc4/streamlink-ttvlol#24]
setting a proxy list like ttv-lol-pro new update , maybe a good idea
![ttv](https://user-images.githubusercontent.com/22505242/213271557-b807967d-69ce-4d1c-bbd6-849c64bdcd6b.png)

**Comment by Sokoloft** [comment]
I would think this is possible, but idk for sure. Having the user point to a txt, ini, or json file with an array would be the ideal way. This is however up to @2bc4

**Comment by 2bc4** [comment]
Sure I'll do this.

>Having the user point to a txt, ini, or json file with an array would be the ideal way.

How about `--twitch-proxy-playlist=URL1,URL2,URL3,URL4,etc`? Streamlink supports comma separated args so it would be easier to implement.

**Comment by DannyDarth** [comment]
With luminous would you still need to have the luminous server up?

**Comment by Sokoloft** [comment]
> With luminous would you still need to have the luminous server up?

It depends on if you're using the local hosted server or not. If you're using the servers posted in the above screenshot then no since they aren't hosted on your computer.
