### ISSUE TITLE
Please re-enable luminous support

### ISSUE THREAD

**Issue by thinkpad4** [2bc4/streamlink-ttvlol#29]
Just added the latest version and I get a error when using luminous proxy.  I never had a issue using luminous.  Please add support back.  If some people can't use it, then they should just not use it, don't deny everyone the option of using luminous when some haven't had any issues with it.  Thank you very much

**Comment by 2bc4** [comment]
I didn't change any code, I only removed the usage instructions from the readme. I have no plans of forbidding the usage of luminous or any servers supporting the TTV.LOL API. If it doesn't work then that could be a bug, what's the issue you're encountering?

**Comment by thinkpad4** [comment]
I made a major  derp
