### ISSUE TITLE
twitch proxy not working

### ISSUE THREAD

**Issue by DannyDarth** [2bc4/streamlink-ttvlol#32]
so i had to re install twitch gui and it seems like its not working for me anymore with the proxy.

is it still --twitch-proxy-playlist=https://api.ttv.lol? or is https://eu.luminous.dev?

Getting vlc could not start. Either the command line options were invalid or no  plugins were found.

**Comment by 2bc4** [comment]
You can use either of those. 

>seems like its not working for me anymore with the proxy

Do you mean you're getting ads, or something else like the player isn't opening?

**Comment by DannyDarth** [comment]
player isnt opening at all

**Comment by 2bc4** [comment]
That seems like a VLC error, not a streamlink one. Make sure you're passing the flags to streamlink and not to VLC. I can try to help if you show your streamlink-twitch-gui settings.

**Comment by DannyDarth** [comment]
https://i.imgur.com/OhH6k2x.png

**Comment by 2bc4** [comment]
That seems correct. Did this error also appear without passing `--twitch-proxy-playlist` in custom parameters? Just to test, what happens if you remove everything from custom parameters and try to open a stream?

**Comment by DannyDarth** [comment]
> That seems correct. Did this error also appear without passing `--twitch-proxy-playlist` in custom parameters? Just to test, what happens if you remove everything from custom parameters and try to open a stream?

stream loads fine without the custom params

**Comment by 2bc4** [comment]
I see. Are there any errors in the logs? The log file should be located at `%TMP%\streamlink-twitch-gui\logs` on Windows.

**Comment by DannyDarth** [comment]
`[2023-03-29T05:12:04.744Z][error][Application]
Ember error: TypeError: Failed to fetch

[2023-03-29T05:12:07.769Z][error][Application]
Ember error: TypeError: Failed to fetch

[2023-03-29T16:53:11.340Z][error][Application]
Ember error: TypeError: Failed to fetch
`

**Comment by 2bc4** [comment]
> https://i.imgur.com/OhH6k2x.png

Oops. That wasn't correct after a second look, my bad. The issue is that you're passing `--twitch-proxy-playlist` in the `Player` tab. You need to move it to `Custom Parameters` in the `Streaming` tab.

**Comment by DannyDarth** [comment]
there is no option for custom params

**Comment by 2bc4** [comment]
You need to check `Enable advanced settings and features` in the `Main` tab before that box appears in `Streaming`.

**Comment by 2bc4** [comment]
I'll close this since the issue is resolved. Feel free to reopen/open another issue if you encounter any more issues.
