### ISSUE TITLE
TTVLOL v2 Proxy Support

### ISSUE THREAD

**Issue by kpg-anon** [2bc4/streamlink-ttvlol#38]
**https://github.com/younesaassila/ttv-lol-pro**

It looks like the original [ttvlol api](https://api.ttv.lol) has been taken down. I've been getting 500 internal server error for the past week or so. I tried the alternate proxies mentioned [here](https://github.com/younesaassila/ttv-lol-pro/discussions/37) and [here](https://github.com/younesaassila/ttv-lol-pro/discussions/130) using the --twitch-proxy-playlist flag but none of them work

**Comment by Sokoloft** [comment]
Try [luminous-ttv](https://github.com/AlyoshaVasilieva/luminous-ttv). Either host it yourself or try the eu public url. ```https://eu.luminous.dev```

It was linked in the readme.md but likely removed to make things less confusing.

**Comment by kpg-anon** [comment]
> Try [luminous-ttv](https://github.com/AlyoshaVasilieva/luminous-ttv). Either host it yourself or try the eu public url. `https://eu.luminous.dev`
> 
> It was linked in the readme.md but likely removed to make things less confusing.

`--twitch-proxy-playlist=https://eu.luminous.dev`

That works for me, thanks
