### ISSUE TITLE
Unable to load streams

### ISSUE THREAD

**Issue by retraenn** [2bc4/streamlink-ttvlol#39]
Today I was suddenly unable to load streams, I thought it was the proxy playlist I was using (ttv.lol and luminous) but when I remove those options and try to load the stream normally I get this error:

> Streamlink Twitch plugin (2bc4 fork). Please report issues to https://github.com/2bc4/streamlink-ttvlol/issues
> Found matching plugin twitch for URL twitch.tv/avoidingthepuddle
> Traceback (most recent call last):
> File "C:\Users\user\AppData\Local\Streamlink\pkgs\streamlink\plugins\twitch.py", line 733, in _access_token

**Comment by 2bc4** [comment]
Upstream issue, it also happens without this patch. It seems like twitch is up to something. Both luminous and ttvlol servers started failing requests at the same time as well.

**Comment by DannyDarth** [comment]
nooooo we need this to work >.<

**Comment by 2bc4** [comment]
Nothing can be done here unfortunately. Hopefully the playlist proxy servers find a workaround, but if they (understandably) can't or are unwilling to then this project is dead.

I'll just put a big warning in the readme until further notice.

**Comment by Sokoloft** [comment]
Someone posted a java script that is supposed to pull the information needed, however I have no idea how to use it. Can find it here. https://github.com/streamlink/streamlink/issues/5370#issuecomment-1571848566

**Comment by brian6932** [comment]
You can bypass Twitch's Kasada client-integrity checks by using a token generated from a TV CID
[How to do so can be found here](https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/issues/94#issuecomment-1360683876)

**Comment by 2bc4** [comment]
Yes that would have to be done on their side. If it comes down to it, I don't think it would be difficult to add that to luminous at least for private instances.

**Comment by DannyDarth** [comment]
using this header "--twitch-api-header Client-ID=ue6666qo983tsx6so1t0vnawi233wa" seems to have fixed the problem. Atleast for now.

**Comment by Sokoloft** [comment]
wtf. So now that there is a workaround twitch rolled back the changes. My streamlink is working without the ```Client-ID``` header. As well as my old version of luminous-ttv. What gives? Maybe they see people worked around it and are going to reimplement it later? 

https://github.com/streamlink/streamlink/issues/5370#issuecomment-1572804535

**Comment by Sokoloft** [comment]
> Hey it's working for me again?

Yes. That is what I pointed out. So twitch is up to something. They're likely in talks with the kasada company to close openings people have found like the ```Client-ID``` header that was found. I'm assuming they rolled back the changes for now to later reimplement once they give it more dev.

**Comment by 2bc4** [comment]
Interesting. Well, I'll reopen this when everything breaks again.

**Comment by Sokoloft** [comment]
Is relevant to the issue. 

https://github.com/streamlink/streamlink/issues/5370#issuecomment-1572883416

So its a warning.
