### ISSUE TITLE
streamlink error

### ISSUE THREAD

**Issue by DannyDarth** [2bc4/streamlink-ttvlol#40]
Started Getting this error today. Im using Streamlink 5.5.1 Could this be the case?

![image](https://github.com/2bc4/streamlink-ttvlol/assets/81840598/349cbf69-6990-4722-aa28-13cc7da0c649)

**Comment by Sokoloft** [comment]
Did you re-execute the command to download this custom twitch.py? 

```powershell
$null= New-Item -ItemType Directory -Path .\AppData\Roaming\streamlink\plugins -Force; iwr -Uri 'https://github.com/2bc4/streamlink-ttvlol/releases/latest/download/twitch.py' -OutFile .\AppData\Roaming\streamlink\plugins\twitch.py

```

**Comment by DannyDarth** [comment]
I fixed it

**Comment by Sokoloft** [comment]
> I fixed it

What was the issue? Just didn't have the twtich.py?

**Comment by DannyDarth** [comment]
> > I fixed it
> 
> What was the issue? Just didn't have the twtich.py?

Well i didnt think i would work with 5.5.1 so i reverted back to 5.4.0 and reinstalled the twitch.py. Works fine now.

**Comment by Sokoloft** [comment]
> > > I fixed it
> > 
> > 
> > What was the issue? Just didn't have the twtich.py?
> 
> Well i didnt think i would work with 5.5.1 so i reverted back to 5.4.0 and reinstalled the twitch.py. Works fine now.

I'm on 5.5.1 and its working just fine. You just have to ensure you re-apply the modified twitch.py with the powershell command I posted here earlier and also in the readme.md.

**Comment by DannyDarth** [comment]
> > > > I fixed it
> > > 
> > > 
> > > What was the issue? Just didn't have the twtich.py?
> > 
> > 
> > Well i didnt think i would work with 5.5.1 so i reverted back to 5.4.0 and reinstalled the twitch.py. Works fine now.
> 
> I'm on 5.5.1 and its working just fine. You just have to ensure you re-apply the modified twitch.py with the powershell command I posted here earlier and also in the readme.md.

gotcha I'll try it again.

**Comment by 2bc4** [comment]
>Well i didnt think i would work with 5.5.1 so i reverted back to 5.4.0

For future reference, the version number is just what release it's based on. Streamlink hasn't updated the twitch plugin since 5.4.0 so that's why it's stuck there.
