### ISSUE TITLE
Any new updates about the http proxy support?

### ISSUE THREAD

**Issue by thinkpad4** [2bc4/streamlink-ttvlol#42]
Hi, I saw the http proxy branch and I am looking forward to using normal proxies with steamlink, any news on the progress of that branch?  I think I read that you said it doesn't block ads yet, I tried it with a ttvlolpro v2 proxy and it didn't block ads at all.   Just wanted to ask how is it going.   Thank you very much

**Comment by 2bc4** [comment]
It is stalled and needs more research.

**Comment by thinkpad4** [comment]
Thanks for letting me know
