### ISSUE TITLE
I get a error with the latest version

### ISSUE THREAD

**Issue by thinkpad4** [2bc4/streamlink-ttvlol#46]
@2bc4 I get this error: [plugins.twitch][info] streamlink-ttvlol d314c5b8-master
[plugins.twitch][info] Please report issues to https://github.com/2bc4/streamlin
k-ttvlol/issues
[cli][info] Found matching plugin twitch for URL twitch.tv/mira
[plugins.twitch][info] Using playlist proxy 'https://eu.luminous.dev'
[plugins.twitch][error] Unable to open URL: https://eu.luminous.dev/live/mira?pl
ayer=twitchweb&type=any&allow_source=true&allow_audio_only=true&allow_spectre=fa
lse&fast_bread=true (request() got an unexpected keyword argument 'keywords')
error: No playable streams found on this URL: twitch.tv/mira

With the version [Fix plugin args not being passed](https://github.com/2bc4/streamlink-ttvlol/commit/b5b23fa25fd4af233a1c2d8d55567dd8984d5f2d)

**Comment by 2bc4** [comment]
The master branch requires git streamlink, currently with at least commit streamlink/streamlink@d314c5b8. Are you running that?

**Comment by 2bc4** [comment]
Maybe I should put that in the readme somewhere. It usually works without git streamlink but when upstream does a big change like recently it will break on normal releases.

**Comment by thinkpad4** [comment]
Well that explains it.  I had a backup of the last version of this.  The new Streamlink release says it's gonna break a lot of things so I'll still with what works until either you add something I wanna try or Streamlink stabilizes

**Comment by 2bc4** [comment]
If I add something noteworthy before the next streamlink version I'll make a new release that's compatible with 5.5.1. So far it has just been refactors and log output stuff so I didn't see a reason to make a new release yet.


Anyways I'll close this now
