### ISSUE TITLE
Save volume level on Re-execution of Streamlink

### ISSUE THREAD

**Issue by PsycloneTM** [2bc4/streamlink-ttvlol#47]
It's really annoying changing the volume back down. But I don't want the volume to be set down by default only on that instants of watching stream.

**Comment by Sokoloft** [comment]
> It's really annoying changing the volume back down. But I don't want the volume to be set down by default only on that instants of watching stream.

What do you mean? I use it on windows with VLC. I don't have this issue. What player are you using? Please leave more information in the future.

**Comment by PsycloneTM** [comment]
> > It's really annoying changing the volume back down. But I don't want the volume to be set down by default only on that instants of watching stream.
> 
> What do you mean? I use it on windows with VLC. I don't have this issue. What player are you using? Please leave more information in the future.

im using mpv

**Comment by Sokoloft** [comment]
> Im using mpv on windows

As a temporary solution you could edit MPV's config file. Adjusting the default volume to a level you wouldn't have to turn up. I use MPV on my Linux systems and I don't have this issue. So it could be something with your overall configuration. You could also try VLC on windows.

@2bc4 Would be able to troubleshoot more so. You could also fork this and add the functionality you're wanting yourself. However I think this is a config issue on your end. Maybe you're using a different player input? Use standard input if so and see if it differs.

Good luck.

**Comment by 2bc4** [comment]
Unfortunately this isn't realistically possible from Streamlink. Streamlink doesn't know what the player volume is, and there isn't a common API to query it.

mpv doesn't save the volume but there's a few mpv plugins that can do that for you. See https://github.com/mpv-player/mpv/issues/1913.

**Comment by PsycloneTM** [comment]
> Unfortunately this isn't realistically possible from Streamlink. Streamlink doesn't know what the player volume is, and there isn't a common API to query it.
> 
> mpv doesn't save the volume but there's a few mpv plugins that can do that for you. See [mpv-player/mpv#1913](https://github.com/mpv-player/mpv/issues/1913).
> 
> > I use MPV on my Linux systems and I don't have this issue.
> 
> Likely because pulseaudio/pipewire is restoring the last volume for mpv.

ok thanks

**Comment by PsycloneTM** [comment]
> 

I prefer mpv more customizability and the ui is better
