### ISSUE TITLE
error: No playable streams found on this URL

### ISSUE THREAD

**Issue by rightsaid** [2bc4/streamlink-ttvlol#48]
Version 6.0.0-20230720,  Using --twitch-ttvlol I get the error: 

[plugins.twitch][info] streamlink-ttvlol d70fe487-master
[plugins.twitch][info] Please report issues to https://github.com/2bc4/streamlink-ttvlol/issues
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/lirik
[plugins.twitch][info] Using playlist proxy 'https://api.ttv.lol'
[plugins.twitch][error] Unable to open URL: https://api.ttv.lol/playlist/lirik.m3u8%3Fplayer%3Dtwitchweb%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3Dtrue (523 Server Error:  for url: https://api.ttv.lol/playlist/lirik.m3u8%3Fplayer%3Dtwitchweb%26type%3Dany%26allow_source%3Dtrue%26allow_audio_only%3Dtrue%26allow_spectre%3Dfalse%26fast_bread%3Dtrue)
error: No playable streams found on this URL: https://www.twitch.tv/lirik

*****
Using other arguments ends up with errors too

**Comment by 2bc4** [comment]
TTVLOL server seems to be dead right now. `--twitch-proxy-playlist=https://as.luminous.dev` is working for me.

**Comment by rightsaid** [comment]
Ok, thank you!
