### ISSUE TITLE
twitch-proxy-m3u8 breaks streamlink config parsing because of number

### ISSUE THREAD

**Issue by 2bc4** [2bc4/streamlink-ttvlol#5]
Adding `twitch-proxy-m3u8` to the streamlink config (`$XDG_CONFIG_HOME/.config/streamlink/config`) seems to prepend `3u8=` to the beginning of the URL. Maybe in the future change the flag to something without a number such as `--twitch-proxy-playlist`.

**Comment by DannyDarth** [comment]
what does adding the proxy do?
