### ISSUE TITLE
any fix to this error?

### ISSUE THREAD

**Issue by PepeLUL** [2bc4/streamlink-ttvlol#50]
![alacritty_WXPMqqHnIw](https://github.com/2bc4/streamlink-ttvlol/assets/19637313/763e799e-55df-4519-8d1a-3b8b02f4a747)

**Comment by 2bc4** [comment]
I could be wrong but it looks like you have an mismatched version of Streamlink. If you're using the latest release it requires Streamlink 6.0.0 or higher.

**Comment by PepeLUL** [comment]
uninstalled the older version it works now thanks 👍
