### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DannyDarth** [2bc4/streamlink-ttvlol#54]
Guessing this isnt updated to the most latest version:

https://i.imgur.com/R7ZRaN1.png

**Comment by 2bc4** [comment]
This with 6.2.0-20230914?

**Comment by DannyDarth** [comment]
> This with [6.2.0-20230914](https://github.com/2bc4/streamlink-ttvlol/releases/tag/6.2.0-20230914)?

it ism I believe 6.2.1 released

**Comment by Sokoloft** [comment]
> > This with [6.2.0-20230914](https://github.com/2bc4/streamlink-ttvlol/releases/tag/6.2.0-20230914)?
> 
> it is I believe 6.2.1 released

There is no 6.2.1 version. You must mean 6.2.0-1. Double check with ```streamlink --version``` in powershell. Also try reinstalling streamlink and then run the powershell command in this repo for the custom twitch.py file. 

iirc I had this issue a few days ago and just had to update to 6.2.0-1.

**Comment by DannyDarth** [comment]
oh mine says 6.1.0 thats my problem thanks
