### ISSUE TITLE
perfprod proxies block requests from Python 3.8 Streamlink

### ISSUE THREAD

**Issue by eccccco** [2bc4/streamlink-ttvlol#57]
It does not work with the V1 perfprod proxies anymore. It broke this week and was fine before. The luminous.dev servers still fetch a stream but with ads (They never really filtered ads for me).

C:\Windows\System32>"C:\Program Files\StreamlinkPortable\streamlink-6.4.2-1-py38
-x86_64\bin\streamlink" --no-config --twitch-proxy-playlist=https://lb-eu2.cdn-p
erfprod.com twitch.tv/lirik 720p60
[plugins.twitch][info] streamlink-ttvlol 6.3.0-20231025 (6.4.2)
[plugins.twitch][info] Please report issues to https://github.com/2bc4/streamlin
k-ttvlol/issues
[cli][info] Found matching plugin twitch for URL twitch.tv/lirik
[plugins.twitch][info] Using playlist proxy 'https://lb-eu2.cdn-perfprod.com'
[plugins.twitch][error] Unable to open URL: https://lb-eu2.cdn-perfprod.com/play
list/lirik.m3u8%3Fallow_source%3Dtrue%26allow_audio_only%3Dtrue%26fast_bread%3Dt
rue (403 Client Error: Forbidden for url: https://lb-eu2.cdn-perfprod.com/playli
st/lirik.m3u8%3Fallow_source%3Dtrue%26allow_audio_only%3Dtrue%26fast_bread%3Dtru
e)
error: No playable streams found on this URL: twitch.tv/lirik

**Comment by 2bc4** [comment]
I can't reproduce. Is it possible those servers blocked your IP address or something?

**Comment by eccccco** [comment]
I'll do some further investigation and report back.

**Comment by zGato** [comment]
Can't seem to be able to reproduce it. I do apply rate-limits to the proxies, but the error code shouldn't be 403 but 429 as per HTTP standards.

Also hitting the rate-limit is just a matter of waiting 1 minute, and to an average user, it's basically impossible to hit without wanting to.

**Comment by eccccco** [comment]
I found the culprit: I am using the Windows 7 streamlink version that supports Python 3.8 and not 3.11. This PC is mainly used for twitch streams and is still running windows 7. On my win10 PC it works fine with the Python 3.11 streamlink version and also doesn't work with the 3.8 Python version. (streamlink-6.5.0-2-py38-x86_64)

Something must have changed server side that broke the use of streamlink with Python 3.8. I only tested the portable versions.

I don't use a VPN but tested ProtonVPN to see if it has any impact on the issue.

**Comment by 2bc4** [comment]
Good find, I can reproduce that. The http request is the same so it must be something lower level that the perfprod servers don't like about the request.

**Comment by zGato** [comment]
It seems like the request is made without any proper user agent? If any of you both can get me a Cloudflare Ray ID error I may be able to investigate further, or tell me the streamer name you tried to proxy and got error 403 so I can check on the logs :)

**Comment by eccccco** [comment]
All streamer names that i tested did not work (e.g. Lirik, Summit1g, Sacriel, ...). I would guess it does not work for any stream with the Python 3.8 Streamlink version.

Just tried adding a custom user agent like this without positive result (not sure if my syntax for the user-agent was correct):

`"C:\Program Files\StreamlinkPortable\streamlink-6.4.2-1-py38-x86_64\bin\streamlink" --no-config --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/120.0" --twitch-proxy-playlist=https://lb-eu2.cdn-perfprod.com twitch.tv/lirik 720p60`

**Comment by zGato** [comment]
Cloudflare did pick up your user agent and I can see your request being blocked due to being 100% automated (bot) as per what Cloudflare tells me. People using your ISP (DTAG) and AT&T are huge spammers on my proxies and most likely Cloudflare is catching what it can (I'm literally getting 300-500k flagged requests per day from them)

Please try using this UA: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0`

**Comment by eccccco** [comment]
DTAG is a big ISP in my country but it didn't even work when I used Proton VPN (tested US, NL and JP Servers).

I tried your suggested UA on the channel 'Giantwaffle' this time. Same results: 
- Does not work with streamlink Py3.8
`"C:\Program Files\StreamlinkPortable\streamlink-6.4.2-1-py38-x86_64\bin\streamlink" --no-config --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0" --twitch-proxy-playlist=https://lb-eu2.cdn-perfprod.com twitch.tv/giantwaffle 720p60`

- Does work with Streamlink Py3.11(modded embeds for win7) with and without custom UA

**Comment by zGato** [comment]
I'll investigate further. I still recommend you to upgrade to Windows 10. But obviously I don't intend to block old system users.

**Comment by eccccco** [comment]
It's not you who is blocking old system users. it's the Python devs. My other PCs that I don't use for watching streams are up to date of course. The old PC that is only used for streams wouldn't be able to handle the current win 10 build which is almost as bloated as windows 11. For example Win 7 boots up in 30 secs without ssd on this machine. Only option would be to switch to Linux.

@2bc4 Feel free to close this issue, as it obviously isn't a ttv-lol-plugin issue but rather a Streamlink issue. And I found a workaround for my situation.

**Comment by 2bc4** [comment]
Alrighty
