### ISSUE TITLE
Error and I don't know what I'm missing.

### ISSUE THREAD

**Issue by nwyr** [2bc4/streamlink-ttvlol#58]
I installed the latest streamlink from pip and overwrite the twitch.py ​​file with 6.6.0-20240216.
Or do I have to install something extra to use it? I don't know. Thanks for your help

<img width="793" alt="error image" src="https://github.com/2bc4/streamlink-ttvlol/assets/25812455/664d88cb-f28c-40f7-8e39-7f4da95c16b4">

**Comment by 2bc4** [comment]
Not sure why but it seems to only happen if you overwrite streamlink's `twitch.py`. You need to sideload the streamlink-ttvlol `twitch.py` by putting it in `~/.local/share/streamlink/plugins` instead.

**Comment by nwyr** [comment]
Thank you very much, I fixed it as you said. Now it's work great.
It's strange that I usually edit plugin files to make them echo or change the code a little. It was no problem. I didn't think I'd have to sideload like this lol.
