### ISSUE TITLE
403 Client Error: Forbidden using public cdn-perfprod proxies

### ISSUE THREAD

**Issue by rouspreda** [2bc4/streamlink-ttvlol#60]
Hello. Lately I've been getting 403 Client Error: Forbidden errors using the cdn-perfprod public proxies listed on the GitHub page:

> C:\Users\[username]>streamlink --twitch-proxy-playlist=https://lb-na.cdn-perfprod.com https://twitch.tv/patty
> [session][info] Plugin twitch is being overridden by C:\Users\[username]\AppData\Roaming\streamlink\plugins\twitch.py
> [plugins.twitch][info] streamlink-ttvlol 6.7.3-20240415 (6.7.4)
> [plugins.twitch][info] Please report issues to https://github.com/2bc4/streamlink-ttvlol/issues
> [cli][info] Found matching plugin twitch for URL https://twitch.tv/patty
> [plugins.twitch][info] Using playlist proxy 'https://lb-na.cdn-perfprod.com'
> [plugins.twitch][error] Unable to open URL: https://lb-na.cdn-perfprod.com/playlist/patty.m3u8%3Fallow_source%3Dtrue%26allow_audio_only%3Dtrue%26fast_bread%3Dtrue (403 Client Error: Forbidden for url: https://lb-na.cdn-perfprod.com/playlist/patty.m3u8%3Fallow_source%3Dtrue%26allow_audio_only%3Dtrue%26fast_bread%3Dtrue)
> error: No playable streams found on this URL: https://twitch.tv/patty

It works just fine using the luminous servers:

> C:\Users\[username]>streamlink --twitch-proxy-playlist=https://eu.luminous.dev https://twitch.tv/patty
> [session][info] Plugin twitch is being overridden by C:\Users\[username]\AppData\Roaming\streamlink\plugins\twitch.py
> [plugins.twitch][info] streamlink-ttvlol 6.7.3-20240415 (6.7.4)
> [plugins.twitch][info] Please report issues to https://github.com/2bc4/streamlink-ttvlol/issues
> [cli][info] Found matching plugin twitch for URL https://twitch.tv/patty
> [plugins.twitch][info] Using playlist proxy 'https://eu.luminous.dev'
> Available streams: audio_only, 160p (worst), 360p, 480p, 720p60, 1080p60 (best)

The perfprod [status site](https://status.cdn-perfprod.com/) says everything is normal.

Unsure if this is an issue with this plugin, the perfprod servers, or something else entirely. I even tried this on a VPN, thinking I was IP banned for some reason. It will work once, but the same error pops up the 2nd time I try to make another proxy connection.

**Comment by 2bc4** [comment]
All of them are showing offline right now on the status page, may be related.

**Comment by rouspreda** [comment]
Thank you for the reply, & thank you for creating & maintaining this plugin. 

I still get 403 Client Error: Forbidden messages here & there, but overall it is working again.

**Comment by 2bc4** [comment]
I'll add that those servers are known to temporarily IP ban if you do too many requests but you shouldn't run into that during normal use. I've never gotten a 403 on my end unfortunately so I don't think it's caused by this.

**Comment by rouspreda** [comment]
Ok, so those servers are known to temporarily IP ban. Good to know. Thank you.

Context: I only do 480p30, 720p30, and/or audio only streams; 60fps streams give me vertigo. The lb-eu5 server has been my go-to since Jan 2024 & never used it behind a VPN. Never any issues outside the maintenance windows. Then this weekend, the 403 errors. As I am typing this out, I am still getting the 403 errors off & on & now my `--twitch-proxy-playlist` lists all the cdn-perfprod servers minus the NA & SA servers. 

My guess is zGato is doing something on his end with his V1 servers, or something happened, etc. From what I can tell, his last post on [#37](https://github.com/younesaassila/ttv-lol-pro/discussions/37) says `"V1 is deprecated and not supported"`, though his V1 proxy servers are still running & maintained. My original concern was an issue with your plugin & zGato's V1 servers. If you are not getting the error, then it's a "my end" problem.

Thank you again for your reply & your help with this error.

**Comment by zGato** [comment]
> Ok, so those servers are known to temporarily IP ban. Good to know. Thank you.
> 
> Context: I only do 480p30, 720p30, and/or audio only streams; 60fps streams give me vertigo. The lb-eu5 server has been my go-to since Jan 2024 & never used it behind a VPN. Never any issues outside the maintenance windows. Then this weekend, the 403 errors. As I am typing this out, I am still getting the 403 errors off & on & now my `--twitch-proxy-playlist` lists all the cdn-perfprod servers minus the NA & SA servers.
> 
> My guess is zGato is doing something on his end with his V1 servers, or something happened, etc. From what I can tell, his last post on [#37](https://github.com/younesaassila/ttv-lol-pro/discussions/37) says `"V1 is deprecated and not supported"`, though his V1 proxy servers are still running & maintained. My original concern was an issue with your plugin & zGato's V1 servers. If you are not getting the error, then it's a "my end" problem.
> 
> Thank you again for your reply & your help with this error.

If you're still experiencing issues, feel free to DM me on Discord: `zgato_` and I'll try to help you if the issue is on the server's end.
TTV LOL PRO V1 is deprecated and not supported, however, my proxies are supported and actively maintained, but I can't guarantee they "block" ads and that sort of stuff. The proxies don't cost me much to maintain, so why bother and remove them if they still work for some people using this and PurpleTV :)

**Comment by rouspreda** [comment]
> If you're still experiencing issues, feel free to DM me on Discord: zgato_ and I'll try to help you if the issue is on the server's end.
> TTV LOL PRO V1 is deprecated and not supported, however, my proxies are supported and actively maintained, but I can't guarantee they "block" ads and that sort of stuff. The proxies don't cost me much to maintain, so why bother and remove them if they still work for some people using this and PurpleTV :)

Hello zGato & thank you for the reply.

I just created a Discord account & sent a friend request. I am still getting the 403 errors & have been using the `luminious.dev` servers.

**Comment by rouspreda** [comment]
@zGato -

I contacted Discord support as to why I cannot join your sever & received the following:

> I've checked the invite link in our system and can confirm the link is valid. If it is still showing up as invalid on your end, your IP address is likely banned from the server. Could you ask one of the moderators to clear all bans in Server Settings > Bans? Restart the client afterwards.
>  
> Keep in mind that if you have an IP address that was used at any point by a user who was banned, you might be banned because of that.
>  
> Also, if you were a member of the server in the past, a "ghost" version of your account may still be a member. This will prevent you from joining again. Have the mods check their user list to make sure your Discord Tag isn't on it. If it is, and you're not on the server, it could be that you weren't fully kicked originally. Once your "ghost" is kicked, you should be able to join again.
>  
> Another option is that a moderation bot has your Discord Tag in its blacklist. You can ask the mods to check each bot's blacklist to ensure that your Discord Tag is not on it.

If you're still willing to help me troubleshoot, please let me know. I'd hate to put more work on your plate helping me figure out Discord as well.

**Comment by zGato** [comment]
@rouspreda just send me a friend request and a DM, if your account is new you'll be perma kicked/banned from my discord servers.

**Comment by rouspreda** [comment]
@zGato done. My display name is the same here - `rouspreda`

![zGato_discord_friend_invite_pending](https://github.com/2bc4/streamlink-ttvlol/assets/115921344/9898af61-a6d7-4d80-936b-022d372480ad)

When I try to DM you, I get an error. Here's the error again:
![zGato_discord_DM_error](https://github.com/2bc4/streamlink-ttvlol/assets/115921344/b65e06e1-e167-4f55-83ea-ffc48867350a)

**Comment by zGato** [comment]
Send the request back again (cancel and send it again) doesn't seem like it shows on my end.

**Comment by zGato** [comment]
Someone else reported me this issue again, and after taking another deep look, seems like I got a fix for it.

So if anyone was affected, you can give it a try now and let me know, enjoy :)
