### ISSUE TITLE
unrecognized arguments

### ISSUE THREAD

**Issue by DannyDarth** [2bc4/streamlink-ttvlol#63]
Getting unrecognized arguments with the custom command. --twitch-proxy-playlist=https://as.luminous.dev....

or any of the proxies for that matter.

**Comment by DannyDarth** [comment]
got it to work I think. didn't realize I had to make a new folder. must be something new

**Comment by DannyDarth** [comment]
> how exactly did you fix your setup? I am having the same issue after updating my setup.

It says it in the description on the main page in github

> Manually
> 
> Navigate to:
> 
> C:\Users\%username%\AppData\Roaming\streamlink
> 
> Then create the plugins folder and drop the twitch.py inside of it.

**Comment by super-lurker** [comment]
> > Manually
> > Navigate to:
> > C:\Users%username%\AppData\Roaming\streamlink
> > Then create the plugins folder and drop the [twitch.py](http://twitch.py) inside of it.

I use the portable version, so I just overwrite the default twitch plugin, but I did the appdata folder and still got the same result.

**Comment by DannyDarth** [comment]
> > > Manually
> > > Navigate to:
> > > C:\Users%username%\AppData\Roaming\streamlink
> > > Then create the plugins folder and drop the [twitch.py](http://twitch.py) inside of it.
> 
> I use the portable version, so I just overwrite the default twitch plugin, but I did the appdata folder and still got the same result.

not sure then. The plugin hasnt been updated in a couple months.

**Comment by super-lurker** [comment]
> > > > Manually
> > > > Navigate to:
> > > > C:\Users%username%\AppData\Roaming\streamlink
> > > > Then create the plugins folder and drop the [twitch.py](http://twitch.py) inside of it.
> > 
> > 
> > I use the portable version, so I just overwrite the default twitch plugin, but I did the appdata folder and still got the same result.
> 
> not sure then. The plugin hasnt been updated in a couple months.

are you using the latest streamlink? and do you also by chance use streamlink GUI? that's how I have mine setup

**Comment by 2bc4** [comment]
At the moment I don't have a windows install so I can't test portable streamlink but you should be able to overwrite `streamlink/plugins/twitch.py` if you also delete the `streamlink/plugins/_plugins.json` file. Not sure why overriding through appdata isn't working.
